apiVersion: v1
kind: Service
metadata:
  name: {{ include "pimcore.fullname" . }}-nginx
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.nginx.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

    {{- if .Values.nginx.backendConfig.enabled }}
    cloud.google.com/backend-config: '{"default":"{{ include "pimcore.fullname" . }}-nginx"}'
    {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
  selector:
      app.kubernetes.io/name: {{ include "pimcore.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-nginx
