apiVersion: v1
kind: Service
metadata:
  name: {{ include "pimcore.fullname" . }}-nginx
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.nginx.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
  selector:
      app.kubernetes.io/name: {{ include "pimcore.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-nginx
