apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-filestore-data-staging-claim
  namespace: pimcore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: gcp-filestore-data-staging
