apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-filestore-data-staging
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  csi:
    driver: filestore.csi.storage.gke.io
    volumeAttributes:
      ip: 10.1.1.1
      volume: gcp_data_staging_k8
    volumeHandle: modeInstance/us-east4-a/data-staging-fs/gcp_data_staging_k8
    persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
