apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pimcore.fullname" . }}-php-fpm-d-zzzz-www-pool-conf
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
data:
  zzzz-www-pool.conf: |
    [www]
    user = {{ .Values.php.phpUser.userName }}
    group = {{ .Values.php.phpUser.groupName }}
    listen = 0.0.0.0:9000
    {{- with .Values.php.fpmPool }}
    pm = {{ .pm }}
    pm.max_children = {{ .pmMaxChildren }}
    pm.start_servers = {{ .pmStartServers }}
    pm.min_spare_servers = {{ .pmMinSpareServers }}
    pm.max_spare_servers = {{ .pmMaxSpareServers }}
    pm.max_requests = {{ .pmMaxRequests }}
    pm.process_idle_timeout = {{ .pmProcessIdleTimeout }}
    {{- end }}
