# /usr/local/etc/php/conf.d/30-pimcore.ini
# to override important values from upsream 20-pimcore.ini, to protect us from potential upstream changes
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pimcore.fullname" . }}-php-conf-d-30-pimcore-ini
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
data:
  30-pimcore.ini: |
    memory_limit = ${PHP_MEMORY_LIMIT}
    max_execution_time = ${PHP_MAX_EXECUTION_TIME}
    error_reporting = ${PHP_ERROR_REPORTING}
    display_errors = ${PHP_DISPLAY_ERRORS}
    display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS}
    post_max_size = ${PHP_POST_MAX_SIZE}
    upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}

    opcache.enable = ${OPCACHE_ENABLE}
    opcache.enable_cli = ${OPCACHE_ENABLE_CLI}
    opcache.memory_consumption = ${OPCACHE_MEMORY_CONSUMPTION}
    opcache.max_accelerated_files = ${OPCACHE_MAX_ACCELERATED_FILES}
    opcache.validate_timestamps = ${OPCACHE_VALIDATE_TIMESTAMPS}
    opcache.consistency_checks = ${OPCACHE_CONSISTENCY_CHECKS}
