apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pimcore.fullname" . }}-initialize-dotenv
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
type: Opaque
data:
  {{ with .Values.pvc.data.initFromRepo }}
  PIMCORE_INIT_REPO_GIT_USER: {{ .gitUserName | default "git" | b64enc }}
  PIMCORE_INIT_REPO_GIT_TOKEN: {{ .gitPersonalAccessToken | b64enc }}
  {{- end }}

