apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pimcore.fullname" . }}-initialize-dotenv
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
type: Opaque
data:
  {{ with .Values.pvc.data.initFromRepo }}
  PIMCORE_INIT_REPO_GIT_USER: {{ .gitUserName | default "git" | b64enc }}
  PIMCORE_INIT_REPO_GIT_TOKEN: {{ .gitPersonalAccessToken | b64enc }}
  {{- end }}
  {{- with .Values.pvc.data.composerAuth }}
  COMPOSER_AUTH: {{ . | b64enc }}
  {{- end }}
  {{- with ((.Values.pvc.data.gitExtraHeader).host) }}
  GIT_CONFIG_COUNT: {{ "1" | b64enc }}
  GIT_CONFIG_KEY_0: {{ printf "http.%s.extraheader" . | b64enc }}
  GIT_CONFIG_VALUE_0: {{ ($.Values.pvc.data.gitExtraHeader).value | b64enc }}
  {{- end }}

