apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-mariadb-pdb
  namespace: pimcore
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: mysql
      app.kubernetes.io/component: primary
