apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pimcore.fullname" . }}-migrate
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/name: {{ include "pimcore.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-migrate
    spec:
      {{- with .Values.php.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pimcore.serviceAccountName" . }}
      restartPolicy: Never
      initContainers:
        {{- include "pimcore.initContainers.wait-for-mysql" . | nindent 12 }}
        {{- include "pimcore.initContainers.wait-for-pimcore-installed" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.php.image.registry }}:{{ .Values.php.image.tag }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "pimcore.fullname" . }}-installation-env
            - secretRef:
                name: {{ include "pimcore.fullname" . }}-dotenv
          command: ["/bin/sh", "-c"]
          args:
            - >
              cd /var/www/pimcore &&
              ./bin/console doctrine:migrations:migrate --no-interaction &&
              ./bin/console assets:install
          securityContext:
            runAsUser: {{ .Values.php.phpUser.uid }}
            runAsGroup: {{ .Values.php.phpUser.gid }}
          volumeMounts:
            - name: php-ini
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: php-conf-d-30-pimcore-ini
              mountPath: /usr/local/etc/php/conf.d/30-pimcore.ini
              subPath: 30-pimcore.ini
            - name: php-fpm-conf
              mountPath: /usr/local/etc/php-fpm.conf
              subPath: php-fpm.conf
            - name: php-fpm-d-zzzz-www-pool-conf
              mountPath: /usr/local/etc/php-fpm.d/zzzz-www.conf
              subPath: zzzz-www-pool.conf
            - name: pimcore-data
              mountPath: /var/www/pimcore
              subPath: {{ .Values.pvc.data.subPath }}
            {{- include "pimcore.customConfigFiles.volumeMounts" . | nindent 12 }}
      volumes:
        - name: pimcore-data
          persistentVolumeClaim:
            claimName: {{ template "pimcore.dataClaimName" . }}
        - name: php-ini
          configMap:
            name: {{ template "pimcore.fullname" . }}-php-ini
        - name: php-conf-d-30-pimcore-ini
          configMap:
            name: {{ template "pimcore.fullname" . }}-php-conf-d-30-pimcore-ini
        - name: php-fpm-conf
          configMap:
            name: {{ template "pimcore.fullname" . }}-php-fpm-conf
        - name: php-fpm-d-zzzz-www-pool-conf
          configMap:
            name: {{ template "pimcore.fullname" . }}-php-fpm-d-zzzz-www-pool-conf
      {{- include "pimcore.customConfigFiles.volumes" . | nindent 6 }}
